import { env } from "@/config/env"
import { km, type LngLat } from "@/lib/geo"

export type ScenarioId = "t0" | "t6" | "t12"
export type Method = "uniform" | "greedy" | "exact" | "qaoa_sim" | "qaoa_ibm"
export type RiskLevel = "low" | "moderate" | "high" | "severe" | null
export type Point = [number, number]

export interface Cell {
  lng: number
  lat: number
  risk: number
  level: RiskLevel
}

export interface Candidate {
  id: number
  name: string
  lng: number
  lat: number
  region: "west" | "east"
}

export interface Scenario {
  id: ScenarioId
  label: string
  grid: { lon0: number; lon1: number; lat0: number; lat1: number; dlon: number; dlat: number }
  cells: Cell[]
  candidates: Candidate[]
  rivers: { krishna: Point[]; krishnaBranch: Point[]; budameru: Point[] }
  coast: Point[]
  city: { name: string; lng: number; lat: number }
  coverKm: number
  splitLng: number
  uniformPlan: number[]
}

export interface Sample {
  bits: string
  energy: number
  prob: number
  feasible: boolean
  optimal: boolean
}

export interface RegionResult {
  region: "west" | "east"
  status: "solved" | "reused" | "hardware"
  qubits: number
  k: number
  p: number
  shots: number
  zzTerms?: number
  costEvals: number
  timeS: number
  warmStarted: boolean
  params: { gammas: number[]; betas: number[]; energyScale: number }
  trace: { eval: number; cvar: number; best: number }[]
  qubo: number[][]
  candidateIds: number[]
  feasibleFrac: number
  randomFeasibleFrac: number
  foundOptimum: boolean
  bestBits: string | null
  bestEnergy: number | null
  optimumEnergy: number
  selection: number[]
  topSamples: Sample[]
  mass?: number
  depth?: number
  twoQubitGates?: number
}

export interface SolveResult {
  method: Method
  scenario: ScenarioId
  k: number
  selection: number[]
  coverage: number
  exactCoverage: number
  ratio: number
  timeS?: number
  plansEvaluated?: number
  regions?: Record<"west" | "east", RegionResult>
  backend?: string
  jobId?: string
  qpuSeconds?: number | null
  offline?: boolean
}

export type Benchmark = Record<
  Exclude<Method, "qaoa_ibm">,
  { coverage: number; ratio: number; timeS: number; selection: number[] }
>

export interface Health {
  ok: boolean
  qiskit: boolean
  ibmReady: boolean
  reason?: string
}

export interface SolveRequest {
  scenario: ScenarioId
  k: number
  method: Method
  p: number
  shots: number
  local: boolean
  previous?: { scenario: ScenarioId; regions: SolveResult["regions"] }
}

export const SCENARIOS: { id: ScenarioId; short: string; label: string }[] = [
  { id: "t0", short: "T0", label: "Forecast issued" },
  { id: "t6", short: "T+6 h", label: "Budameru surge" },
  { id: "t12", short: "T+12 h", label: "Delta flooding" },
]

export const METHODS: { id: Method; label: string; quantum: boolean }[] = [
  { id: "qaoa_sim", label: "QAOA · statevector simulator", quantum: true },
  { id: "qaoa_ibm", label: "QAOA · IBM Heron QPU", quantum: true },
  { id: "exact", label: "Exact search (baseline)", quantum: false },
  { id: "greedy", label: "Greedy heuristic (baseline)", quantum: false },
  { id: "uniform", label: "Uniform spacing (static plan)", quantum: false },
]

/** Set VITE_API_URL to use the live backend. Without it the app runs on the recorded results in public/snapshot.json. */
const API = env.apiUrl
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms))

interface Snapshot {
  scenarios: Record<ScenarioId, Scenario>
  solves: Record<ScenarioId, SolveResult>
  benchmarks: Record<ScenarioId, Benchmark>
}
let snapPromise: Promise<Snapshot> | null = null
/** Offline fallback: public/snapshot.json, generated by backend/make_snapshot.py. */
function snap(): Promise<Snapshot> {
  snapPromise ??= fetch(`${import.meta.env.BASE_URL}snapshot.json`).then((r) => r.json() as Promise<Snapshot>)
  return snapPromise
}

async function call<T>(path: string, init?: RequestInit, timeoutMs = 120_000): Promise<T> {
  const ctrl = new AbortController()
  const timer = setTimeout(() => ctrl.abort(), timeoutMs)
  try {
    const res = await fetch(`${API}${path}`, { ...init, signal: ctrl.signal })
    const body = await res.json()
    if (!res.ok) throw new Error(body.error ?? `HTTP ${res.status}`)
    return body as T
  } finally {
    clearTimeout(timer)
  }
}

export async function getHealth(): Promise<Health | null> {
  if (!API) return null
  try {
    return await call<Health>("/health", undefined, 3000)
  } catch {
    return null
  }
}

export async function getScenario(id: ScenarioId, online: boolean): Promise<Scenario> {
  if (!online) return (await snap()).scenarios[id]
  return call<Scenario>(`/scenario?id=${id}`)
}

export async function solve(req: SolveRequest, online: boolean): Promise<SolveResult> {
  if (online) {
    return call<SolveResult>("/quantum/solve", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(req),
    })
  }
  await wait(300)
  if (req.k !== 6) throw new Error("Recorded results cover k = 6 only. Start the backend to change k.")
  if (req.method === "qaoa_ibm") throw new Error("IBM hardware runs need the backend with a saved IBM Quantum account.")
  const SNAP = await snap()
  if (req.method === "qaoa_sim") return { ...SNAP.solves[req.scenario], offline: true }
  const b = SNAP.benchmarks[req.scenario][req.method]
  const exact = SNAP.benchmarks[req.scenario].exact
  return {
    method: req.method, scenario: req.scenario, k: 6, selection: b.selection, coverage: b.coverage,
    exactCoverage: exact.coverage, ratio: b.ratio, timeS: b.timeS, offline: true,
  }
}

export async function getBenchmark(id: ScenarioId, k: number, online: boolean): Promise<Benchmark> {
  if (!online) {
    await wait(1200)
    if (k !== 6) throw new Error("Offline snapshot covers k = 6 only.")
    return (await snap()).benchmarks[id]
  }
  return call<Benchmark>(`/quantum/benchmark?id=${id}&k=${k}`)
}

/** Risk weight used by the optimiser: (risk - 0.3)^1.5 above the low-risk floor. */
export const cellWeight = (r: number) => Math.max(0, r - 0.3) ** 1.5

export function siteCoverage(sc: Scenario, siteId: number) {
  const s = sc.candidates[siteId]
  const total = sc.cells.reduce((a, c) => a + cellWeight(c.risk), 0)
  const own = sc.cells
    .filter((c) => km([c.lng, c.lat], [s.lng, s.lat]) <= sc.coverKm)
    .reduce((a, c) => a + cellWeight(c.risk), 0)
  return own / total
}

/** Risk at a point: the cell it falls in, or 0 outside the grid. */
export function riskAt(sc: Scenario, p: LngLat) {
  const { lon0, lat1, dlon, dlat } = sc.grid
  const i = Math.floor((p[0] - lon0) / dlon)
  const j = Math.floor((lat1 - p[1]) / dlat)
  const c = sc.cells.find((x) => Math.floor((x.lng - lon0) / dlon) === i && Math.floor((lat1 - x.lat) / dlat) === j)
  return c?.risk ?? 0
}

export const pct = (v: number, d = 1) => `${(v * 100).toFixed(d)}%`
